apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::495345689226:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AWG2KAHE4XC8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::495345689226:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-15T07:09:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1705"
  uid: 5c6b68bd-d08a-4d46-9012-3f675467e978
